# Generated by Django 2.2 on 2019-05-30 21:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('con_agg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='author',
            new_name='article_url',
        ),
        migrations.RemoveField(
            model_name='content',
            name='text',
        ),
        migrations.AddField(
            model_name='websitelist',
            name='header_type',
            field=models.CharField(default='h2', max_length=10),
        ),
        migrations.AddField(
            model_name='websitelist',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='websitelist',
            name='web_hardlink',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 30, 21, 30, 57, 718629, tzinfo=utc)),
        ),
    ]
