# Generated by Django 2.2 on 2019-04-27 04:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('con_agg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitelist',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 27, 4, 51, 49, 933933, tzinfo=utc)),
        ),
    ]
