# Generated by Django 2.2 on 2019-04-27 04:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('con_agg', '0002_websitelist_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitelist',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
