# Generated by Django 2.2 on 2019-05-30 21:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('con_agg', '0002_auto_20190530_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 30, 21, 39, 40, 781009, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='websitelist',
            name='web_hardlink',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
