# Generated by Django 2.2 on 2019-04-30 16:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('con_agg', '0003_auto_20190426_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='author',
            new_name='article_url',
        ),
        migrations.RemoveField(
            model_name='content',
            name='text',
        ),
        migrations.AlterField(
            model_name='content',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 30, 16, 53, 34, 678269, tzinfo=utc)),
        ),
    ]
