# Generated by Django 2.2 on 2019-05-03 20:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('con_agg', '0005_auto_20190503_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 3, 20, 15, 28, 637055, tzinfo=utc)),
        ),
    ]
