# Generated by Django 2.2 on 2019-04-30 18:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('con_agg', '0005_auto_20190430_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 30, 18, 39, 18, 881936, tzinfo=utc)),
        ),
    ]
