# Generated by Django 2.2 on 2019-05-02 00:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('con_agg', '0006_auto_20190430_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 2, 0, 17, 22, 455549, tzinfo=utc)),
        ),
    ]
