# Generated by Django 2.2 on 2019-05-02 00:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('con_agg', '0007_auto_20190501_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 2, 0, 45, 3, 757310, tzinfo=utc)),
        ),
    ]
