# Generated by Django 2.2 on 2019-05-02 10:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('con_agg', '0008_auto_20190501_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 2, 10, 56, 21, 486831, tzinfo=utc)),
        ),
    ]
